In [22]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/organizations/uciml/sms-spam-collection-dataset/spam.csv

In [23]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [24]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/organizations/uciml/sms-spam-collection-dataset/spam.csv

In [25]:
df = pd.read_csv(
    "/kaggle/input/datasets/organizations/uciml/sms-spam-collection-dataset/spam.csv",
    encoding="latin1"
)

df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [26]:
df = df[['v1', 'v2']]

df.columns = ['label', 'text']

df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [27]:
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

df.head()

   label                                               text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [28]:
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['text'])

y = df['label']

In [29]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [33]:
#model-1
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

nb.fit(X_train, y_train)

pred = nb.predict(X_test)
nb_acc = accuracy_score(y_test, pred)

print("Accuracy:",  nb_acc)

Accuracy: 0.9623318385650225

In [36]:
#model-2
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train, y_train)

pred = lr.predict(X_test)
lr_acc = accuracy_score(y_test, pred)

print("Accuracy:", lr_acc)

Accuracy: 0.9632286995515695

In [39]:
from sklearn.svm import LinearSVC

svm = LinearSVC()

svm.fit(X_train, y_train)

pred = svm.predict(X_test)
svm_acc = accuracy_score(y_test, pred)

print("Accuracy:",svm_acc)

Accuracy: 0.9802690582959641

In [41]:
#model-4
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

rfc_acc = accuracy_score(y_test, pred)
print("Accuracy:",rfc_acc )

Accuracy: 0.9757847533632287

In [42]:
#model-5
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

pred = knn.predict(X_test)
knn_acc = accuracy_score(y_test, pred)
print("Accuracy:", knn_acc)

Accuracy: 0.9130044843049328

In [44]:
results = {
    "Model":[
        "Naive Bayes",
        "Logistic Regression",
        "SVM",
        "Random Forest",
        "KNN"
    ],

    "Accuracy":[
        nb_acc,
        lr_acc,
        svm_acc,
        rfc_acc,
        knn_acc
    ]
}

pd.DataFrame(results)

                 Model  Accuracy
0          Naive Bayes  0.962332
1  Logistic Regression  0.963229
2                  SVM  0.980269
3        Random Forest  0.975785
4                  KNN  0.913004

we can conclude that svm has provided us with the highest accuracy.